- name: Activate {{ repo.name }} (Drone adding webhook to GitHub repo)
  uri:
    method: POST
    url: https://{{ proxy_domain_external }}/api/repos/{{ github_owner }}/{{ repo.name }}
    status_code:
    - 200
    headers:
      Authorization: Bearer {{ github_pat }}

- name: Update Drone configuration for {{ repo.name }}
  uri:
    method: PATCH
    url: https://{{ proxy_domain_external }}/api/repos/{{ github_owner }}/{{ repo.name }}
    body_format: json
    body: |
      {
        "config_path": ".drone.yaml",
        "protected": false,
        "trusted": false,
        "timeout": 60,
        "visibility": "private"
      }
    return_content: yes
    status_code:
    - 200
    headers:
      Authorization: Bearer {{ github_pat }}
