# ansible-playbook deploy.yaml -i inventory/prod/hosts --vault-id ~/.tokens/master_id

- hosts: drone
  roles:
    - application
    - traefik
    
  tasks:
    - include_role:
        name: application
        tasks_from: make_data_dir

    - include_role:
        name: application
        tasks_from: make_config_dir

    - name: Ensure ssh directory exists
      file:
        state: directory
        path: '{{ config_dir }}/.ssh'
        mode: '0700'
        owner: root
        group: root
      become: yes


    - name: Copy over Drone Runner .env file for use in Drone steps and plugin containers
      copy:
        content: |
          REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
          TZ=America/Los_Angeles
        dest: '{{ config_dir }}/drone.env'
        owner: root
        group: root
        mode: '0644'
      become: yes

    - name: Copy over Drone Runner ssh config file for use in Drone steps and plugin containers
      copy:
        content: |
          Host github.com
            StrictHostKeyChecking no
            User git
            IdentityFile /root/.ssh/id_rsa_github
        dest: '{{ config_dir }}/.ssh/config'
        owner: root
        group: root
        mode: '0644'
      become: yes

    - name: Copy over Drone Runner ssh private key file for use in Drone steps and plugin containers
      copy:
        content: '{{ automation_id_rsa }}'
        dest: '{{ config_dir }}/.ssh/id_rsa_github'
        owner: root
        group: root
        mode: '0600'
      become: yes

    - include_role:
        name: docker
        tasks_from: stack_deploy

    - name: Wait for https://{{ proxy_domain_external }}/welcome to be found
      uri:
        method: GET
        url: https://{{ proxy_domain_external }}/welcome
        status_code:
          - 200
        headers:
          Authorization: Bearer {{ github_pat }}
      register: _result
      until: ("status" in _result) and (_result.status == 200 or _result.status == 401)
      retries: 30
      delay: 1

    - name: "Waiting for GitHub admin to sign into https://{{ proxy_domain_external }}/ (Tip: Use incognito window )"
      uri:
        method: GET
        url: https://{{ proxy_domain_external }}/api/user/repos
        status_code:
          - 200
        headers:
          Authorization: Bearer {{ github_pat }}
      register: _result
      until: '"status" in _result and _result.status == 200 and _result.json | length > 0'
      retries: 240
      delay: 1

