- name: 'Get current cron jobs for {{ repo.name }}'
  uri:
    method: GET
    url: https://{{ proxy_domain_external }}/api/repos/{{ github_owner }}/{{ repo.name }}/cron
    return_content: yes
    status_code:
    - 200
    headers:
      Authorization: Bearer {{ github_pat }}
  register: result

- set_fact:
    cron_jobs_current: '{{ result | json_query("{url: url, names: json[*].name}") }}'

- name: Delete cron jobs for {{ repo.name }}
  uri:
    method: DELETE
    url: '{{ cron_jobs_current.url }}/{{ secret_name }}'
    return_content: yes
    status_code:
    - 204
    headers:
      Authorization: Bearer {{ github_pat }}
  loop: '{{ cron_jobs_current.names }}'
  loop_control:
    loop_var: secret_name

- name: Create cron jobs for {{ repo.name }}
  uri:
    method: POST
    url: https://{{ proxy_domain_external }}/api/repos/{{ github_owner }}/{{ repo.name }}/cron
    body_format: 'json'
    body: |
      {
        "name": "{{ cron_job.name }}",
        "expr": "{{ cron_job.expr }}",
        "branch":  "{{ cron_job.branch }}"
      }
    return_content: yes
    status_code:
    - 200
    headers:
      Authorization: Bearer {{ github_pat }}
  loop: '{{ repo.cron_jobs }}'
  loop_control:
    loop_var: cron_job
  ignore_errors: yes
